/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type * as lib from './lib'
export type { lib }
import type * as nftBridge from './nft-bridge'
export type { nftBridge }
import type * as test from './test'
export type { test }
import type * as token from './token'
export type { token }
export type { Environment } from './Environment'
export type { IEnvironment } from './IEnvironment'
export type { IStakeManager } from './IStakeManager'
export type { StakeManager } from './StakeManager'
export type { System } from './System'
