/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export { IL2ERC20Bridge__factory } from './IL2ERC20Bridge__factory'
export { IL2ERC721Bridge__factory } from './IL2ERC721Bridge__factory'
