/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import { Contract, Signer, utils } from 'ethers'
import type { Provider } from '@ethersproject/providers'
import type {
	INFTBridgeMainchain,
	INFTBridgeMainchainInterface,
} from '../../../contracts/nft-bridge/INFTBridgeMainchain'

const _abi = [
	{
		anonymous: false,
		inputs: [
			{
				indexed: true,
				internalType: 'uint256',
				name: 'depositIndex',
				type: 'uint256',
			},
			{
				indexed: true,
				internalType: 'address',
				name: 'mainchainERC721',
				type: 'address',
			},
			{
				indexed: true,
				internalType: 'uint256',
				name: 'tokenId',
				type: 'uint256',
			},
			{
				indexed: false,
				internalType: 'uint256',
				name: 'sidechainId',
				type: 'uint256',
			},
			{
				indexed: false,
				internalType: 'address',
				name: 'mainFrom',
				type: 'address',
			},
			{
				indexed: false,
				internalType: 'address',
				name: 'sideTo',
				type: 'address',
			},
		],
		name: 'DepositInitiated',
		type: 'event',
	},
	{
		anonymous: false,
		inputs: [
			{
				indexed: true,
				internalType: 'uint256',
				name: 'depositIndex',
				type: 'uint256',
			},
		],
		name: 'DepositRejected',
		type: 'event',
	},
	{
		anonymous: false,
		inputs: [
			{
				indexed: true,
				internalType: 'uint256',
				name: 'depositIndex',
				type: 'uint256',
			},
			{
				indexed: true,
				internalType: 'uint256',
				name: 'sidechainId',
				type: 'uint256',
			},
			{
				indexed: true,
				internalType: 'uint256',
				name: 'withdrawalIndex',
				type: 'uint256',
			},
			{
				indexed: false,
				internalType: 'address',
				name: 'mainchainERC721',
				type: 'address',
			},
			{
				indexed: false,
				internalType: 'address',
				name: 'sideFrom',
				type: 'address',
			},
			{
				indexed: false,
				internalType: 'address',
				name: 'mainTo',
				type: 'address',
			},
		],
		name: 'WithdrawalFailed',
		type: 'event',
	},
	{
		anonymous: false,
		inputs: [
			{
				indexed: true,
				internalType: 'uint256',
				name: 'depositIndex',
				type: 'uint256',
			},
			{
				indexed: true,
				internalType: 'uint256',
				name: 'sidechainId',
				type: 'uint256',
			},
			{
				indexed: true,
				internalType: 'uint256',
				name: 'withdrawalIndex',
				type: 'uint256',
			},
			{
				indexed: false,
				internalType: 'address',
				name: 'mainchainERC721',
				type: 'address',
			},
			{
				indexed: false,
				internalType: 'address',
				name: 'sideFrom',
				type: 'address',
			},
			{
				indexed: false,
				internalType: 'address',
				name: 'mainTo',
				type: 'address',
			},
		],
		name: 'WithdrawalFinalized',
		type: 'event',
	},
	{
		inputs: [
			{
				internalType: 'address',
				name: 'mainchainERC721',
				type: 'address',
			},
			{
				internalType: 'uint256',
				name: 'tokenId',
				type: 'uint256',
			},
			{
				internalType: 'uint256',
				name: 'sidechainId',
				type: 'uint256',
			},
			{
				internalType: 'address',
				name: 'sideTo',
				type: 'address',
			},
		],
		name: 'deposit',
		outputs: [],
		stateMutability: 'nonpayable',
		type: 'function',
	},
	{
		inputs: [
			{
				internalType: 'uint256',
				name: 'mainchainId',
				type: 'uint256',
			},
			{
				internalType: 'uint256',
				name: 'depositIndex',
				type: 'uint256',
			},
			{
				internalType: 'uint256',
				name: 'sidechainId',
				type: 'uint256',
			},
			{
				internalType: 'uint256',
				name: 'withdrawalIndex',
				type: 'uint256',
			},
			{
				internalType: 'address',
				name: 'sideFrom',
				type: 'address',
			},
			{
				internalType: 'address',
				name: 'mainTo',
				type: 'address',
			},
		],
		name: 'finalizeWithdrawal',
		outputs: [],
		stateMutability: 'nonpayable',
		type: 'function',
	},
	{
		inputs: [
			{
				internalType: 'uint256',
				name: 'depositIndex',
				type: 'uint256',
			},
		],
		name: 'getDepositInfo',
		outputs: [
			{
				components: [
					{
						internalType: 'address',
						name: 'mainchainERC721',
						type: 'address',
					},
					{
						internalType: 'uint256',
						name: 'tokenId',
						type: 'uint256',
					},
					{
						internalType: 'address',
						name: 'mainFrom',
						type: 'address',
					},
					{
						internalType: 'address',
						name: 'mainTo',
						type: 'address',
					},
				],
				internalType: 'struct INFTBridgeMainchain.DepositInfo',
				name: '',
				type: 'tuple',
			},
		],
		stateMutability: 'view',
		type: 'function',
	},
	{
		inputs: [
			{
				internalType: 'uint256',
				name: 'mainchainId',
				type: 'uint256',
			},
			{
				internalType: 'uint256',
				name: 'depositIndex',
				type: 'uint256',
			},
		],
		name: 'rejectDeposit',
		outputs: [],
		stateMutability: 'nonpayable',
		type: 'function',
	},
	{
		inputs: [
			{
				internalType: 'uint256',
				name: 'mainchainId',
				type: 'uint256',
			},
			{
				internalType: 'address',
				name: 'newRelayer',
				type: 'address',
			},
		],
		name: 'transferMainchainRelayer',
		outputs: [],
		stateMutability: 'nonpayable',
		type: 'function',
	},
]

export class INFTBridgeMainchain__factory {
	static readonly abi = _abi
	static createInterface(): INFTBridgeMainchainInterface {
		return new utils.Interface(_abi) as INFTBridgeMainchainInterface
	}
	static connect(address: string, signerOrProvider: Signer | Provider): INFTBridgeMainchain {
		return new Contract(address, _abi, signerOrProvider) as INFTBridgeMainchain
	}
}
