/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
	BaseContract,
	BigNumber,
	BytesLike,
	CallOverrides,
	PopulatedTransaction,
	Signer,
	utils,
} from 'ethers'
import type { FunctionFragment, Result } from '@ethersproject/abi'
import type { Listener, Provider } from '@ethersproject/providers'
import type {
	TypedEventFilter,
	TypedEvent,
	TypedListener,
	OnEvent,
	PromiseOrValue,
} from '../../common'

export interface TokenInterface extends utils.Interface {
	functions: {
		'SOAS()': FunctionFragment
		'WOAS()': FunctionFragment
	}

	getFunction(nameOrSignatureOrTopic: 'SOAS' | 'WOAS'): FunctionFragment

	encodeFunctionData(functionFragment: 'SOAS', values?: undefined): string
	encodeFunctionData(functionFragment: 'WOAS', values?: undefined): string

	decodeFunctionResult(functionFragment: 'SOAS', data: BytesLike): Result
	decodeFunctionResult(functionFragment: 'WOAS', data: BytesLike): Result

	events: {}
}

export interface Token extends BaseContract {
	connect(signerOrProvider: Signer | Provider | string): this
	attach(addressOrName: string): this
	deployed(): Promise<this>

	interface: TokenInterface

	queryFilter<TEvent extends TypedEvent>(
		event: TypedEventFilter<TEvent>,
		fromBlockOrBlockhash?: string | number | undefined,
		toBlock?: string | number | undefined,
	): Promise<Array<TEvent>>

	listeners<TEvent extends TypedEvent>(
		eventFilter?: TypedEventFilter<TEvent>,
	): Array<TypedListener<TEvent>>
	listeners(eventName?: string): Array<Listener>
	removeAllListeners<TEvent extends TypedEvent>(eventFilter: TypedEventFilter<TEvent>): this
	removeAllListeners(eventName?: string): this
	off: OnEvent<this>
	on: OnEvent<this>
	once: OnEvent<this>
	removeListener: OnEvent<this>

	functions: {
		SOAS(overrides?: CallOverrides): Promise<[string]>

		WOAS(overrides?: CallOverrides): Promise<[string]>
	}

	SOAS(overrides?: CallOverrides): Promise<string>

	WOAS(overrides?: CallOverrides): Promise<string>

	callStatic: {
		SOAS(overrides?: CallOverrides): Promise<string>

		WOAS(overrides?: CallOverrides): Promise<string>
	}

	filters: {}

	estimateGas: {
		SOAS(overrides?: CallOverrides): Promise<BigNumber>

		WOAS(overrides?: CallOverrides): Promise<BigNumber>
	}

	populateTransaction: {
		SOAS(overrides?: CallOverrides): Promise<PopulatedTransaction>

		WOAS(overrides?: CallOverrides): Promise<PopulatedTransaction>
	}
}
