/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export type { IL2ERC20Bridge } from './IL2ERC20Bridge'
export type { IL2ERC721Bridge } from './IL2ERC721Bridge'
